#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), 'lib')))

require 'rational'
require 'gosim/view'
require 'rdoc/usage'

if ARGV[0] and File.exists?(ARGV[0])
#  $LOAD_PATH.unshift(File.expand_path(File.dirname(ARGV[0])))

  puts "Loading simulation file: #{File.basename(ARGV[0])}"

  # Tell the view that we are in live sim mode
  GoSim::View::instance.live = true

  # Since there will be events published to the DataSet classes, we need to
  # make sure to correctly flush the Zlib stream
  at_exit { GoSim::Data::DataSetWriter.instance.close() }

  load ARGV[0]
end

GoSim::View.instance.run
